### ISSUE TITLE
[UI] Signup page 

### ISSUE THREAD

**Issue by prakharepo** [prakharepo/campus_placement_app#2]
Currently the signup page is default provided by Django. Can you create a signup page with details like email, password and confirm password with JavaScript validations.

Thanks in Advance

<img width="792" alt="register" src="https://user-images.githubusercontent.com/70509216/94315920-11b34400-ffa1-11ea-8c06-c449b998221d.PNG">

**Comment by codesankalp** [comment]
I will make the pull request for this issue in october. So you can assign me, I want to contribute in your repo actively thanks.

**Comment by codesankalp** [comment]
Means i want to say that you can assign me all issues (where i have commented) and i will make the pull request on 1st of october if you are agree with this. 
Thanks.

**Comment by codesankalp** [comment]
@prakharepo I have used ajax validator to validate this. And i have completed this issue. So it'll be better if you assign it to me because i will make pull request on this on 1st october.

**Comment by prakharepo** [comment]
@codesankalp  I have assigned this issue to you. On 1'st October, please pull the latest version before pushing because we will be making some changes in code. Thanks for contributing.
