### ISSUE TITLE
[UI] CSS and Validations for Login Page

### ISSUE THREAD

**Issue by prakharepo** [prakharepo/campus_placement_app#3]
### Bootstrap CSS and Basic Validations for login page required

<img width="805" alt="login" src="https://user-images.githubusercontent.com/70509216/94317606-4f659c00-ffa4-11ea-841a-97b23c2c40b9.PNG">

Thanks for Helping in Advance

**Comment by codesankalp** [comment]
I will add that validations and styles. Please assign this issue to me i will make the accurate pull request for this.
One question how do you want to validate this means using django validators or javascript?

**Comment by prakharepo** [comment]
@codesankalp  Javascript validations will work. For CSS part you are welcome to apply your own creativity. We are targeting cross platform so please try to use bootstrap classes.
