### ISSUE TITLE
List field in model

### ISSUE THREAD

**Issue by prakharepo** [prakharepo/campus_placement_app#4]
### In Placement/Models.py

Currently there is so much redundancy, storing every application of user separately.

We want a list corresponding to every user which contains name of all applied job profile (Company Name)

**Comment by codesankalp** [comment]
I would like to work on this issue. @prakharepo can you assign me this issue.

**Comment by codesankalp** [comment]
I think this problem can be better solved by Many to many field.
So I am using that.
Also i think that, it is not a problem to store many application for single user because you can easily filter in Django ORM.

**Comment by prakharepo** [comment]
@codesankalp I have used _unique_together_ so a user can only apply for a particular job once, so in the admin panel i got multiple entries for the same user with different applied job and that was fine, but what i wanted is a single entry for a user within that there will be multipe applied jobs. And you can try what you are suggesting if that resolve this issue and also see _your_app view_ used to show applied jobs for a user.

**Comment by codesankalp** [comment]
Yes i have fixed that i am making pull request as hacktober fest is started.
You will love my work because it solved your problem.
