### ISSUE TITLE
Status Feature in Jobprofile

### ISSUE THREAD

**Issue by prakharepo** [prakharepo/campus_placement_app#9]
### New Column Status particular for every user with values -
1. Apply
2. Applied

Currently the same functionality is implemented in yourapp which can be accessed by clicking "Click here to see your applied Applications" on show company page.

Thanks for showing interest in our project

**Comment by codesankalp** [comment]
@prakharepo as i have added the pull request for M2M field in application. I would like to add new column as mentioned.
